apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity
type: Opaque
data:
  DB_ROOT_PASSWORD: U21hcnRDaXR5QFJvb3QjMjAyNg==
  DB_PASSWORD: U21hcnRDaXR5QEFwcCMyMDI2
  JWT_SECRET: U21hcnRDaXR5QEpXVCNTZWNyZXRfSmFrYXJ0YTIwMjYh
  OAUTH_CLIENT_SECRET: U21hcnRDaXR5QE9BdXRoIzIwMjQ=
  OAUTH_INTROSPECTION_API_KEY: U21hcnRDaXR5QEludHJvc3BlY3QjMjAyNg==
  RABBITMQ_PASS: U21hcnRDaXR5QFJhYmJpdCMyMDI2
  MQTT_PASS: U21hcnRDaXR5QE1RVFQjMjAyNg==